# This is a basic workflow to help you get started with Actions

name: Publish Library

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Publish libraries to Github Packages
        env:
          MVN_USERNAME: ${{ secrets.MVN_USERNAME }}
          MVN_PERSONAL_ACCESS_TOKEN: ${{ secrets.MVN_PERSONAL_ACCESS_TOKEN }}
        run: |
          ./gradlew publishReleasePublicationToGitHubPackagesRepository -Pgpr.user=$MVN_USERNAME -Pgpr.key=$MVN_PERSONAL_ACCESS_TOKEN
